[package]
name = "bevy_wireframe"
version = "0.1.0"
edition = "2021"

[dependencies]
# bevy = "0.13.2"
# bevy = { path = "../bevy" }
bevy = { git = "https://github.com/shanecelis/bevy.git" }
bytemuck = "1.15.0"
